-- MySQL Script generated by MySQL Workbench
-- Fri Feb  7 14:17:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Project1OverhillWneryDW
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Project1OverhillWneryDW` ;

-- -----------------------------------------------------
-- Schema Project1OverhillWneryDW
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Project1OverhillWneryDW` DEFAULT CHARACTER SET utf8 ;
USE `Project1OverhillWneryDW` ;

-- -----------------------------------------------------
-- Table `Project1OverhillWneryDW`.`Sales_Agent_Dimension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project1OverhillWneryDW`.`Sales_Agent_Dimension` ;

CREATE TABLE IF NOT EXISTS `Project1OverhillWneryDW`.`Sales_Agent_Dimension` (
  `Employee_ID` VARCHAR(2) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Commission_Rate` DOUBLE NOT NULL,
  PRIMARY KEY (`Employee_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project1OverhillWneryDW`.`Product_Dimension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project1OverhillWneryDW`.`Product_Dimension` ;

CREATE TABLE IF NOT EXISTS `Project1OverhillWneryDW`.`Product_Dimension` (
  `Product ID` INT NOT NULL AUTO_INCREMENT,
  `Production_Code` INT NOT NULL,
  `Brand_Name` VARCHAR(45) NOT NULL,
  `Varieties` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Group` ENUM('Red', 'White') NOT NULL,
  `Unit_Cost(Doz)` DECIMAL(10,2) NOT NULL,
  `Unit_Price(Doz)` DECIMAL(10,2) NOT NULL,
  `Stock_On_Hand` INT NOT NULL,
  `ProdYear` YEAR(4) NOT NULL,
  PRIMARY KEY (`Product ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project1OverhillWneryDW`.`Date_Dimension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project1OverhillWneryDW`.`Date_Dimension` ;

CREATE TABLE IF NOT EXISTS `Project1OverhillWneryDW`.`Date_Dimension` (
  `Date` DATE NOT NULL,
  `Day_Of_Week` ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday') NOT NULL,
  `MonthName` ENUM('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec') NOT NULL,
  `Week_Number` INT NOT NULL,
  `Half_Year` ENUM('1st', '2nd') NOT NULL,
  `Year` YEAR(4) NOT NULL,
  `Season_Name` ENUM('Spring', 'Summer', 'Autumn', 'Winter') NOT NULL,
  `Quarter` INT NOT NULL,
  `DateNumber` INT NOT NULL,
  PRIMARY KEY (`Date`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project1OverhillWneryDW`.`Customer_Dimension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project1OverhillWneryDW`.`Customer_Dimension` ;

CREATE TABLE IF NOT EXISTS `Project1OverhillWneryDW`.`Customer_Dimension` (
  `Customer_ID` INT NOT NULL,
  `Period` VARCHAR(45) NOT NULL,
  `Customer_Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(255) NOT NULL,
  `Suburb` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `Postcode` VARCHAR(45) NOT NULL,
  `Market` ENUM('Vic', 'Int', 'Aus') NOT NULL,
  `Market Description` VARCHAR(45) NOT NULL,
  `CustomerCode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CustomerCode`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project1OverhillWneryDW`.`SalesProfit_Fact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project1OverhillWneryDW`.`SalesProfit_Fact` ;

CREATE TABLE IF NOT EXISTS `Project1OverhillWneryDW`.`SalesProfit_Fact` (
  `Sales_Agent_Dimension_Employee_ID` VARCHAR(2) NOT NULL,
  `Product_Dimension_Product ID` INT NOT NULL,
  `Date_Dimension_Date` DATE NOT NULL,
  `Sale_ID` INT NOT NULL,
  `Line Number` INT NOT NULL,
  `Unit_Price` DECIMAL(10,2) NOT NULL,
  `Sale_Amount_Dollar` DECIMAL(10,2) NOT NULL,
  `Sales_Margin` DECIMAL(10,2) NOT NULL,
  `UnitSales` INT NOT NULL,
  `Commission` DECIMAL(10,2) NOT NULL,
  `Customer_Dimension_CustomerCode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Sale_ID`, `Line Number`),
  CONSTRAINT `fk_SalesProfit_Fact_Sales_Agent_Dimension1`
    FOREIGN KEY (`Sales_Agent_Dimension_Employee_ID`)
    REFERENCES `Project1OverhillWneryDW`.`Sales_Agent_Dimension` (`Employee_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SalesProfit_Fact_Product_Dimension1`
    FOREIGN KEY (`Product_Dimension_Product ID`)
    REFERENCES `Project1OverhillWneryDW`.`Product_Dimension` (`Product ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SalesProfit_Fact_Date_Dimension1`
    FOREIGN KEY (`Date_Dimension_Date`)
    REFERENCES `Project1OverhillWneryDW`.`Date_Dimension` (`Date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SalesProfit_Fact_Customer_Dimension1`
    FOREIGN KEY (`Customer_Dimension_CustomerCode`)
    REFERENCES `Project1OverhillWneryDW`.`Customer_Dimension` (`CustomerCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
